### ISSUE TITLE
BLK999 Unexpected exception: 'PY310'

### ISSUE THREAD

**Issue by Minipada** [peterjc/flake8-black#66]
# Setup
pyproject.toml contains:

```toml
[tool.black]
diff = false
verbose = false
line-length = 100
target-version = ['py38', 'py39', 'py310']
```

flake8-black version: 0.3.3
poetry version: 1.1.13

pre-commit:
```yaml
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          [
            ...
            flake8-black,
            ...
          ]
```

# What I did
running:
```
poetry shell
flake8 ...
```
works

As does `poetry run flake8 ...`

But
```
poetry run pre-commit run flake8 ...
```

returns
```
BLK999 Unexpected exception: 'PY310'
```

Only this extension gives problems, not sure why.
